name: orders-pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Test with Maven
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t orders-service-example:latest .

  sonarqube-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=zionweb_orders-service-example
            -Dsonar.organization=zionwebsonar
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.binaries=target/classes  

  manual-aprove:
    needs: sonarqube-scan
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo "Approving..."

  deploy:
    needs: manual-aprove
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
